"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-08-27 23:27:45.696012

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_listings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('price_usd', sa.String(length=32), nullable=False),
    sa.Column('capability_tags', sa.JSON(), nullable=False),
    sa.Column('protocols', sa.JSON(), nullable=False),
    sa.Column('provider_name', sa.String(length=200), nullable=False),
    sa.Column('is_seed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_listings'))
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('protocol', sa.String(length=16), nullable=False),
    sa.Column('capability', sa.String(length=100), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=False),
    sa.Column('payer', sa.String(length=100), nullable=False),
    sa.Column('pay_to', sa.String(length=100), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('settlement_id', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries'))
    )
    op.create_index(op.f('ix_ledger_entries_protocol'), 'ledger_entries', ['protocol'], unique=False)
    op.create_index(op.f('ix_ledger_entries_service_id'), 'ledger_entries', ['service_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_status'), 'ledger_entries', ['status'], unique=False)
    op.create_index(op.f('ix_ledger_entries_timestamp'), 'ledger_entries', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ledger_entries_timestamp'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_status'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_service_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_protocol'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_table('catalog_listings')
    # ### end Alembic commands ###
