"""llm settings

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-29 06:10:27.317109

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: str | Sequence[str] | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_base_url', sa.String(length=500), nullable=False),
    sa.Column('gateway_base_url', sa.String(length=500), nullable=False),
    sa.Column('client_id', sa.String(length=200), nullable=False),
    sa.Column('client_secret', sa.String(length=500), nullable=False),
    sa.Column('allowed_models', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_settings'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_settings')
    # ### end Alembic commands ###
