"""wallet settings

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-29 15:10:09.911466

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: str | Sequence[str] | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backend', sa.String(length=16), nullable=False),
    sa.Column('circle_api_key', sa.String(length=500), nullable=True),
    sa.Column('circle_entity_secret', sa.String(length=500), nullable=True),
    sa.Column('circle_wallet_id', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet_settings'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_settings')
    # ### end Alembic commands ###
